name = "MHMiLQR"
uuid = "cc6f6f65-08c7-49b2-9c9b-e23214e815ad"
authors = ["Juraj Lieskovsk√Ω <lieskovsky.juraj@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GillMurrayWright81 = "1819ed89-a2b3-41ea-8dbb-b3a776e027cf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
GillMurrayWright81 = "0.1.0"
