[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
MHMiLQR = "cc6f6f65-08c7-49b2-9c9b-e23214e815ad"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
QuadrotorODE = "f87403a7-72d5-42dd-abb3-547112e6cf83"
CartPoleODE = "e298af44-abc3-4c5d-b59c-9d5fcd78a32d"
UCNCartPoleODE = "020fc5a9-7829-4d7f-9758-a9dd5095b6c2"
MeshCatBenchmarkMechanisms = "e83dc370-f0ba-44d1-a240-217e19b8d23b"

[sources]
MHMiLQR = {path = ".."}
QuadrotorODE = {url = "https://github.com/JurajLieskovsky/QuadrotorODE.jl.git"}
CartPoleODE = {url = "https://github.com/JurajLieskovsky/CartPoleODE.jl.git"}
UCNCartPoleODE = {url = "https://github.com/JurajLieskovsky/UCNCartPoleODE.jl.git"}
MeshCatBenchmarkMechanisms = {url = "https://github.com/JurajLieskovsky/MeshCatBenchmarkMechanisms.jl.git"}
